routes:
  - destination: 10.1.7.0
    mask: 30
    passerelle : 
    interface: 10.1.7.1
    distance : 1
  - destination: 172.16.180.0
    mask: 30
    passerelle : 
    interface: 172.16.180.1
    distance : 1
