routes:
  - destination: 10.1.3.0
    mask: 30
    passerelle : 
    interface: 10.1.3.2
    distance : 1
  - destination: 10.1.6.0
    mask: 30
    passerelle : 
    interface: 10.1.6.2
    distance : 1
