routes:
  - destination: 127.0.0.0
    mask: 24
    passerelle : 
    interface: 127.0.0.1
    distance : 1
  - destination: 10.1.1.0
    mask: 30
    passerelle : 
    interface: 10.1.1.2
    distance : 1
    