routes:
  - destination: 10.1.2.0
    mask: 30
    passerelle : 
    interface: 10.1.2.3
    distance : 1
  - destination: 10.1.1.0
    mask: 30
    passerelle : 
    interface: 10.1.1.3
    distance : 1
  - destination: 10.1.3.0
    mask: 30
    passerelle : 
    interface: 10.1.3.3
    distance : 1
  - destination: 10.1.4.0
    mask: 30
    passerelle : 
    interface: 10.1.4.3
    distance : 1
    
