routers:
  - name: R1
    port: 8520
    devices:
      - interface: eth0
        ip: 127.0.0.1
        mask: 24
      - interface: eth1
        ip: 10.1.1.2
        mask: 30
  - name: R2
    port: 8520
    devices:
      - interface: eth0
        ip: 10.1.1.3
        mask: 30
      - interface: eth1
        ip: 10.1.2.3
        mask: 30
      - interface: eth2
        ip: 10.1.3.3
        mask: 30
      - interface: eth4
        ip: 10.1.4.3
        mask: 30
  - name: R3
    port: 8520
    devices:
      - interface: eth0
        ip: 10.1.2.2
        mask: 30
      - interface: eth1
        ip: 10.1.5.2
        mask: 30
  - name: R4
    port: 8520
    devices:
      - interface: eth0
        ip: 10.1.3.2
        mask: 30
      - interface: eth1
        ip: 10.1.6.2
        mask: 30
  - name: R5
    port: 8520
    devices:
      - interface: eth0
        ip: 10.1.5.3
        mask: 30
      - interface: eth1
        ip: 10.1.4.2
        mask: 30
      - interface: eth3
        ip: 10.1.6.3
        mask: 30
  
