routes:
  - destination: 10.1.5.0
    mask: 30
    passerelle : 
    interface: 10.1.5.1
    distance : 1
  - destination: 10.1.4.0
    mask: 30
    passerelle : 
    interface: 10.1.4.2
    distance : 1
  - destination: 10.1.6.0
    mask: 30
    passerelle : 
    interface: 10.1.6.1
    distance : 1
  - destination: 10.1.7.0
    mask: 30
    passerelle : 
    interface: 10.1.7.2
    distance : 1
    
